/* tslint:disable */
/* eslint-disable */
/**
 * diff API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { DiffPrettypRequest } from '../models';
// @ts-ignore
import type { DiffPrettypResponse } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary make a diff (Myers) from two text input
         * @param {DiffPrettypRequest} diffPrettypRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDiffPost: async (diffPrettypRequest: DiffPrettypRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'diffPrettypRequest' is not null or undefined
            assertParamExists('apiDiffPost', 'diffPrettypRequest', diffPrettypRequest)
            const localVarPath = `/api/diff`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(diffPrettypRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary make a diff (Myers) from two text input
         * @param {DiffPrettypRequest} diffPrettypRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDiffPost(diffPrettypRequest: DiffPrettypRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DiffPrettypResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiDiffPost(diffPrettypRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiDiffPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary make a diff (Myers) from two text input
         * @param {DiffPrettypRequest} diffPrettypRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDiffPost(diffPrettypRequest: DiffPrettypRequest, options?: RawAxiosRequestConfig): AxiosPromise<DiffPrettypResponse> {
            return localVarFp.apiDiffPost(diffPrettypRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - interface
 */
export interface DefaultApiInterface {
    /**
     * 
     * @summary make a diff (Myers) from two text input
     * @param {DiffPrettypRequest} diffPrettypRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiDiffPost(diffPrettypRequest: DiffPrettypRequest, options?: RawAxiosRequestConfig): AxiosPromise<DiffPrettypResponse>;

}

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI implements DefaultApiInterface {
    /**
     * 
     * @summary make a diff (Myers) from two text input
     * @param {DiffPrettypRequest} diffPrettypRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiDiffPost(diffPrettypRequest: DiffPrettypRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiDiffPost(diffPrettypRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

